-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module Tog.Raw.Abs where

newtype Name = Name ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)

newtype Empty = Empty ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)

data Module = Module Name Params [Decl]
  deriving (Eq, Ord, Show, Read)

data QName = Qual QName Name | NotQual Name
  deriving (Eq, Ord, Show, Read)

data Decl
    = TypeSig TypeSig
    | FunDef Name [Pattern] FunDefBody
    | Data Name Params DataBody
    | Record Name Params RecordBody
    | Open QName
    | OpenImport Import
    | Import Import
    | Postulate [TypeSig]
    | Module_ Module
  deriving (Eq, Ord, Show, Read)

data Import = ImportNoArgs QName | ImportArgs QName [Arg]
  deriving (Eq, Ord, Show, Read)

data TypeSig = Sig Name Expr
  deriving (Eq, Ord, Show, Read)

data Where = Where [Decl] | NoWhere
  deriving (Eq, Ord, Show, Read)

data Params
    = NoParams | ParamDecl [Binding] | ParamDef [HiddenName]
  deriving (Eq, Ord, Show, Read)

data HiddenName = NotHidden Name | Hidden Name
  deriving (Eq, Ord, Show, Read)

data DataBody
    = DataDecl Name | DataDef [Constr] | DataDeclDef Name [Constr]
  deriving (Eq, Ord, Show, Read)

data RecordBody
    = RecordDecl Name
    | RecordDef Name Fields
    | RecordDeclDef Name Name Fields
  deriving (Eq, Ord, Show, Read)

data Fields = NoFields | Fields [Constr]
  deriving (Eq, Ord, Show, Read)

data Constr = Constr Name Expr
  deriving (Eq, Ord, Show, Read)

data FunDefBody = FunDefNoBody | FunDefBody Expr Where
  deriving (Eq, Ord, Show, Read)

data Telescope = Tel [Binding]
  deriving (Eq, Ord, Show, Read)

data Binding = Bind [Arg] Expr | HBind [Arg] Expr
  deriving (Eq, Ord, Show, Read)

data Expr
    = Lam [Name] Expr
    | Pi Telescope Expr
    | Fun Expr Expr
    | Eq Expr Expr
    | App [Arg]
    | Id QName
  deriving (Eq, Ord, Show, Read)

data Arg = HArg Expr | Arg Expr
  deriving (Eq, Ord, Show, Read)

data Pattern
    = EmptyP Empty | ConP QName [Pattern] | IdP QName | HideP Pattern
  deriving (Eq, Ord, Show, Read)

